### ISSUE TITLE
02 of June - The Minskins

### ISSUE THREAD

**Issue by Bismarck-GM** [Shaqri/The-next-web#1]
## Great job so far! Everything looks amazing! Nice job using em sizing!

- Encapsulate the articles so they maintain aspect ratio within the size of the screen.
- Try to use this https://www.w3schools.com/howto/howto_css_aspect_ratio.asp for aspect ratio of background images.
- Check the specificity of the selector used in MAIN.CSS (i.e. line 394). Better use a class to select those tags.
- Try to commit more often.

<pre>
           (                 ,&&&.
            )                .,.&&
           (  (              \=__/
               )             ,'-'.
         (    (  ,,      _.__|/ /|
          ) /\ -((------((_|___/ |
        (  // | (`'      ((  `'--|
      _ -.;_/ \\--._      \\ \-._/.
     (_;-// | \ \-'.\    <_,\_\`--'|
     ( `.__ _  ___,')      <_,-'__,'
      `'(_ )_)(_)_)' 
</pre>

**Comment by carlosveigadev** [comment]
Thanks for the help guys, we applied most of the suggestions.
=D
